# npx antora --clean --fetch antora-playbook.yml
# or
# npx antora antora-playbook.yml
antora:
  extensions:
  - '@antora/site-generator-ms'
site:
  title: Couchbase Docs Staging
  url: https://docs-staging.couchbase.com
  start_page: home::index.adoc
  robots: disallow
  keys:
    nav_groups: |
      [
        { "title": "Server", "startPage": "home::server.adoc", "components": ["server"] },
        { "title": "Mobile", "startPage": "home::mobile.adoc", "components": ["couchbase-lite", "sync-gateway"] },
        { "title": "Cloud", "startPage": "cloud::index.adoc", "components": ["cloud"] },
        { "title": "Cloud-Native", "startPage": "cloud-native-database::index.adoc", "components": ["cloud-native-database"] },
        { "title": "Autonomous Operator", "components": ["operator"] },
        { "title": "CMOS", "components": ["cmos"] },
        { "title": "Service Broker", "components": ["service-broker"] },
        { "title": "SDKs", "startPage": "home::sdk.adoc", "components": ["*-sdk", "cxx-txns", "elasticsearch-connector", "kafka-connector", "spark-connector", "tableau-connector"] },
        { "title": "Tutorials", "startPage": "tutorials::index.adoc", "components": ["tutorials"] }
      ]
git:
  ensure_git_suffix: false
  fetch_concurrency: 10
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  branches: master
  # NOTE the git@ segment in the URL indicates which repositories are private
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://git@github.com/couchbasecloud/couchbase-cloud
    branches: [main]
    start_path: docs/public
  - url: https://git@github.com/couchbase/couchbase-operator
    branches: [master, 2.3.0-beta, 2.2.x, 2.1.x, 2.0.x, 1.2.x, 1.1.x, 1.0.x]
    start_path: docs/user
asciidoc:
  attributes:
    site-navigation-data-path: _/js/site-navigation-data.js
    enable-cmos: ''
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
    enterprise: https://www.couchbase.com/products/editions[ENTERPRISE EDITION]
    community: https://www.couchbase.com/products/editions[COMMUNITY EDITION]
    sqlpp: SQL++
    kroki-server-url: http://3.91.133.254:9500
    kroki-fetch-diagram: true
  extensions:
  - ./lib/source-url-include-processor.js
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
  - asciidoctor-kroki
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui/releases/download/prod-143/ui-bundle.zip
    #url: https://deploy-preview-xxx--cb-docs-ui.netlify.app/dist/ui-bundle.zip
    #snapshot: true
output:
  dir: ./public
