# $(npm bin)/antora --clean --fetch antora-playbook.yml
site:
  title: Couchbase Docs
  url: https://docs.couchbase.com
  start_page: home::index.adoc
  robots: allow
  keys:
    google_analytics: GTM-MVPNN2
git:
  ensure_git_suffix: false
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  branches: master
  # NOTE the git@ segment in the URL indicates which repositories are private
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://git@github.com/couchbase/docs-analytics
    branches: [release/7.0, release/6.6]
  - url: https://github.com/couchbase/couchbase-cli
    branches: [master, mad-hatter]
    start_path: docs
  - url: https://git@github.com/couchbase/backup
    branches: [master, mad-hatter]
    start_path: docs
  - url: https://github.com/couchbaselabs/cb-swagger
    branches: [release/7.0, release/6.6]
    start_path: docs
  # NOTE docs-server is currently after other server repos so nav key wins
  - url: https://github.com/couchbase/docs-server
    branches: [release/7.0, meta-desc]
  - url: https://github.com/couchbase/docs-sdk-common
    branches: [release/6.6]
  - url: https://github.com/couchbase/docs-sdk-c
    branches: [release/3.1, release/3.0, release/2.10]
  - url: https://github.com/couchbase/docs-txn-cxx
    branches: [release/1.0]
  - url: https://github.com/couchbase/docs-sdk-dotnet
    branches: [release/3.1, release/3.0, release/2.7]
  - url: https://github.com/couchbase/docs-sdk-go
    branches: [release/2.2, release/2.1, release/2.0, release/1.6, release/1.5]
  - url: https://github.com/couchbase/docs-sdk-java
    branches: [release/3.1, release/3.0, release/2.7]
  - url: https://github.com/couchbase/docs-sdk-nodejs
    branches: [release/3.1, release/3.0, release/2.6]
  - url: https://github.com/couchbase/docs-sdk-php
    branches: [release/3.1, release/3.0, release/2.6]
  - url: https://github.com/couchbase/docs-sdk-python
    branches: [release/3.0, release/2.5]
  - url: https://github.com/couchbase/docs-sdk-ruby
    branches: [release/3.0]
  - url: https://github.com/couchbase/docs-sdk-scala
    branches: [release/1.1, release/1.0]
 asciidoc:
  attributes:
    max-include-depth: 10
    page-partial: false
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
    enterprise: https://www.couchbase.com/products/editions[ENTERPRISE EDITION]
    community: https://www.couchbase.com/products/editions[COMMUNITY EDITION]
  extensions:
  - ./lib/source-url-include-processor.js
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://github.com/couchbase/docs-ui-sandbox/releases/download/prod-93/ui-bundle.zip
output:
  dir: ./public
