[build]
command = """\
[[ $(du -s $ANTORA_CACHE_DIR 2>/dev/null | cut -f1 || echo 0) -gt 10000000 ]] && rm -rf $ANTORA_CACHE_DIR; \
if [ -v FONTAWESOME_NPM_TOKEN ]; then echo -e '@fortawesome:registry=https://npm.fontawesome.com/\\n//npm.fontawesome.com/:_authToken=$''{FONTAWESOME_NPM_TOKEN}' > ../scripts/.npmrc; fi; \
(cd ../scripts; npm --no-package-lock i >/dev/null || true); \
if [ -v GITHUB_TOKEN ]; then export GIT_CREDENTIALS=https://$GITHUB_TOKEN:@github.com; fi; \
mkdir public; \
time npx antora --extension=./lib/exclude-private-content-sources-extension.js --fetch --log-file=~+/public/antora.log --redirect-facility=netlify --to-dir=~+/public --url $(if [[ $CONTEXT == 'production' ]]; then echo -n $URL; else echo -n $DEPLOY_PRIME_URL; fi) ../antora-playbook.yml || tail antora.log && \
node ../scripts/populate-icon-defs.js public
"""
ignore = "false"
publish = "public"

[build.environment]
ANTORA_CACHE_DIR = "~+/node_modules/.cache/antora"
NODE_VERSION = "16"
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_FLAGS = "--no-optional"

[context.production.environment]
ALGOLIA_APP_ID = "NI1G57N08Q"
ALGOLIA_API_KEY = "d3eff3e8bcc0860b8ceae87360a47d54"
ALGOLIA_INDEX_NAME = "staging_docs_couchbase"
OPTANON_SCRIPT_URL = "https://cdn.cookielaw.org/consent/288c1333-faac-4514-a8bf-a30b3db0ee32.js"
SHOW_FEEDBACK_BUTTON = "true"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
