[build]
ignore = "false"
publish = "public"

[build.environment]
ANTORA_CACHE_DIR = "node_modules/.cache/antora"
CI = "true"
NODE_VERSION = "10"
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_FLAGS = "--no-optional"

[context.production]
command = """\
mkdir public && \
echo -e '<!DOCTYPE html>\\n<meta http-equiv="refresh" content="0; url=https://docs.couchbase.com">\\n<meta name="robots" content="noindex">\\n<title>Redirect Notice</title>\\n<p>Redirecting to <a href="https://docs.couchbase.com">docs.couchbase.com</a>...</p>' > public/index.html\
"""

[context.deploy-preview]
command = """\
if [ -v FONTAWESOME_NPM_TOKEN ]; then echo -e '@fortawesome:registry=https://npm.fontawesome.com/\\n//npm.fontawesome.com/:_authToken=$''{FONTAWESOME_NPM_TOKEN}' > ../scripts/.npmrc; fi; \
(cd ../scripts; npm --no-package-lock i || true) && \
if [ -v GITHUB_TOKEN ]; then export GIT_CREDENTIALS=https://$GITHUB_TOKEN:@github.com; else node ../scripts/remove-private-content-sources.js ../antora-playbook.yml; fi; \
time node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml || true; \
time node_modules/.bin/antora --generator=@antora/site-generator-ms --redirect-facility=netlify --to-dir=public --url $DEPLOY_PRIME_URL ../antora-playbook.yml && \
node ../scripts/populate-icon-defs.js public\
"""

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
